"""
Django settings for zhh_movie project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')
if ALLOWED_HOSTS == ['']:
    ALLOWED_HOSTS = []

CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
if CSRF_TRUSTED_ORIGINS == ['']:
    CSRF_TRUSTED_ORIGINS = []

SESSION_COOKIE_SECURE=os.getenv("SESSION_COOKIE_SECURE")=="True"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'django_filters',
    "djoser",
    "movie",
    "account",
    "trade",
    "django_celery_beat",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zhh_movie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zhh_movie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "drf_movie",
        "HOST":"localhost",
        "USER":"root",
        "PASSWORD":"root",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
LOCALE_PATHS=[
    Path(BASE_DIR).joinpath("locale")
]

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# STATIC_URL= "/static/"
# STATICFILES_DIRS=[
#     BASE_DIR / "static",
# ]
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 32,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

EMAIL_HOST=os.getenv("EMAIL_HOST")
EMAIL_PORT=os.getenv("EMAIL_PORT")
EMAIL_HOST_USER=os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD=os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

DJOSER={
    "USER_ID_FIELD":"username",
    "LOGIN_FIELD":"email",
    "SEND_ACTIVATION_EMAIL":True,
    "ACTIVATION_URL":"activate/{uid}/{token}",
    "SEND_CONFIRMATION_EMAIL":True,
    "LOGOUT_ON_PASSWORD_CHANGE":True,
    "SERIALIZERS":{
        "user_create": "account.serializers.CustomUserCreateSerializer",
        "current_user": "account.serializers.UserProfileSerializer",
    },
    'TOKEN_MODEL': None,
    "PASSWORD_RESET_CONFIRM_URL":"reset_password/{uid}/{token}",
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND":True,
    "PASSWORD_RESET_CONFIRM_RETYPE":True,
    "SET_PASSWORD_RETYPE":True,
}

from datetime import timedelta
SIMPLE_JWT = {
    # 默认是Bearer
    'AUTH_HEADER_TYPES': ('JWT',),
    # "ACCESS_TOKEN_LIFETIME":timedelta(minutes=5),
    "ACCESS_TOKEN_LIFETIME":timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME":timedelta(days=7),
}

#配置支付宝
#支付宝网关地址
ALIPAY_SERVER_URL=os.getenv("ALIPAY_SERVER_URL")
#应用APPID
ALIPAY_APP_ID=os.getenv("ALIPAY_APP_ID")
#应用私钥
ALIPAY_APP_PRIVATE_KEY=os.getenv("ALIPAY_APP_PRIVATE_KEY")
#支付宝公钥
ALIPAY_PUBLIC_KEY=os.getenv("ALIPAY_PUBLIC_KEY")
#returnURL
ALIPAY_RETURN_URL=os.getenv("ALIPAY_RETURN_URL")
#notifyURL
ALIPAY_NOTIFY_URL=os.getenv("ALIPAY_NOTIFY_URL")
#商户PID
ALIPAY_SELLER_ID=os.getenv("ALIPAY_SELLER_ID")

# 配置Celery
CELERY_BROKER_URL="redis://localhost:6379/0"
CELERY_RESULT_BACKEND="redis://localhost:6379/1"
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_TASK_TRACK_STARTED = True
#30*60是30分钟 60是秒
CELERY_TASK_TIME_LIMIT = 30 * 60