# Generated by Django 6.0 on 2025-12-19 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类管理',
                'db_table': 'category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, verbose_name='电影名称')),
                ('release_year', models.IntegerField(verbose_name='上映年份')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('director', models.CharField(max_length=20, verbose_name='导演')),
                ('scriptwriter', models.CharField(max_length=20, verbose_name='编剧')),
                ('actors', models.CharField(max_length=20, verbose_name='主演')),
                ('region', models.SmallIntegerField(choices=[(1, '中国大陆'), (2, '中国香港'), (3, '中国台湾'), (4, '美国'), (5, '日本'), (6, '韩国'), (7, '法国'), (8, '英国'), (9, '其他')], default=1, verbose_name='地区')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('language', models.CharField(max_length=20, verbose_name='语言')),
                ('duration', models.CharField(max_length=20, verbose_name='时长(集数)')),
                ('alternate_name', models.CharField(max_length=20, verbose_name='电影英文名')),
                ('image_url', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='图片链接')),
                ('rate', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, verbose_name='豆瓣评分')),
                ('review', models.TextField(blank=True, default='', max_length=500, verbose_name='简介')),
                ('is_hot', models.BooleanField(blank=True, choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否热门')),
                ('is_top', models.BooleanField(blank=True, choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否置顶')),
                ('quality', models.SmallIntegerField(blank=True, choices=[(1, '720P'), (2, '1080P'), (3, '4K')], default=1, verbose_name='清晰度')),
                ('subtitle', models.CharField(blank=True, default='', max_length=100, verbose_name='字幕')),
                ('update_info', models.CharField(blank=True, default='', max_length=100, verbose_name='更新信息')),
                ('update_progress', models.CharField(blank=True, default='', max_length=100, verbose_name='更新进度')),
                ('download_info', models.TextField(blank=True, default='', help_text='每个网盘信息占一行', max_length=500, null=True, verbose_name='网盘信息')),
                ('is_show', models.BooleanField(blank=True, choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否显示')),
                ('is_free', models.BooleanField(blank=True, choices=[(False, '否'), (True, '是')], default=False, verbose_name='是否免费')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影管理',
                'db_table': 'movie',
                'ordering': ['id'],
            },
        ),
    ]
