# Generated by Django 6.0 on 2025-12-24 14:09

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True, verbose_name='用户唯一标识')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='邮箱')),
                ('avatar', models.CharField(blank=True, max_length=60, null=True, verbose_name='用户头像')),
                ('is_upgrade', models.IntegerField(default=0, verbose_name='是否升级会员')),
                ('upgrade_time', models.DateField(blank=True, null=True, verbose_name='升级日期')),
                ('expire_time', models.DateField(blank=True, null=True, verbose_name='过期时间')),
                ('upgrade_count', models.IntegerField(default=0, verbose_name='升级次数')),
                ('movie', models.ManyToManyField(to='movie.movie', verbose_name='电影')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'profile',
            },
        ),
    ]
