# Generated by Django 6.0 on 2025-12-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upgrade_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='升级日期'),
        ),
    ]
